export interface LanguageConfig {
  id: string;
  name: string;
  title: string;
  description: string;
  minify: boolean;
  extensions: string[];
}

// Centralized language configuration
export const LANGUAGES: Record<string, LanguageConfig> = {
  c: {
    id: "c",
    name: "C",
    title: "C Formatter and Minifier",
    description: "C code formatter that formats C source code, locally in your browser",
    minify: false,
    extensions: ["c", "h"],
  },
  cpp: {
    id: "cpp",
    name: "C++",
    title: "C++ Formatter and Minifier",
    description: "C++ code formatter that formats C++ source code, locally in your browser",
    minify: false,
    extensions: ["cpp", "cxx", "cc", "hpp", "hxx", "hh"],
  },
  objectivec: {
    id: "objectivec",
    name: "Objective-C",
    title: "Objective-C Formatter and Minifier",
    description: "Objective-C formatter that formats Objective-C source code, locally in your browser",
    minify: false,
    extensions: ["m"],
  },
  objectivecpp: {
    id: "objectivecpp",
    name: "Objective-C++",
    title: "Objective-C++ Formatter and Minifier",
    description: "Objective-C++ formatter that formats Objective-C++ source code, locally in your browser",
    minify: false,
    extensions: ["mm"],
  },
  csharp: {
    id: "csharp",
    name: "C#",
    title: "C# Formatter and Minifier",
    description: "C# code formatter that formats C# source code, locally in your browser",
    minify: false,
    extensions: ["cs"],
  },
  css: {
    id: "css",
    name: "CSS",
    title: "CSS Formatter and Minifier",
    description: "CSS formatter that formats CSS stylesheets, locally in your browser",
    minify: true,
    extensions: ["css"],
  },
  scss: {
    id: "scss",
    name: "SCSS",
    title: "SCSS Formatter and Minifier",
    description: "SCSS formatter that formats SCSS stylesheets, locally in your browser",
    minify: true,
    extensions: ["scss"],
  },
  sass: {
    id: "sass",
    name: "Sass",
    title: "Sass Formatter",
    description: "Sass formatter that formats indented Sass stylesheets, locally in your browser",
    minify: false,
    extensions: ["sass"],
  },
  less: {
    id: "less",
    name: "Less",
    title: "Less Formatter",
    description: "Less formatter that formats Less stylesheets, locally in your browser",
    minify: false,
    extensions: ["less"],
  },
  dart: {
    id: "dart",
    name: "Dart",
    title: "Dart Formatter and Minifier",
    description: "Dart code formatter that formats Dart source code, locally in your browser",
    minify: false,
    extensions: ["dart"],
  },
  go: {
    id: "go",
    name: "Go",
    title: "Go Formatter and Minifier",
    description: "Go code formatter that formats Go source code, locally in your browser",
    minify: false,
    extensions: ["go"],
  },
  html: {
    id: "html",
    name: "HTML",
    title: "HTML Formatter and Minifier",
    description: "HTML formatter that formats HTML markup, locally in your browser",
    minify: true,
    extensions: ["html", "htm"],
  },
  vue: {
    id: "vue",
    name: "Vue",
    title: "Vue Formatter",
    description: "Vue formatter that formats Vue single-file components, locally in your browser",
    minify: false,
    extensions: ["vue"],
  },
  svelte: {
    id: "svelte",
    name: "Svelte",
    title: "Svelte Formatter",
    description: "Svelte formatter that formats Svelte components, locally in your browser",
    minify: false,
    extensions: ["svelte"],
  },
  astro: {
    id: "astro",
    name: "Astro",
    title: "Astro Formatter",
    description: "Astro formatter that formats Astro components, locally in your browser",
    minify: false,
    extensions: ["astro"],
  },
  angular: {
    id: "angular",
    name: "Angular",
    title: "Angular Template Formatter",
    description: "Angular template formatter that formats Angular HTML templates, locally in your browser",
    minify: false,
    extensions: ["component.html"],
  },
  handlebars: {
    id: "handlebars",
    name: "Handlebars",
    title: "Handlebars Formatter",
    description: "Handlebars formatter that formats Handlebars and Glimmer templates, locally in your browser",
    minify: false,
    extensions: ["hbs", "handlebars"],
  },
  jinja: {
    id: "jinja",
    name: "Jinja",
    title: "Jinja Formatter",
    description: "Jinja formatter that formats Jinja templates, locally in your browser",
    minify: false,
    extensions: ["jinja", "jinja2", "j2"],
  },
  twig: {
    id: "twig",
    name: "Twig",
    title: "Twig Formatter",
    description: "Twig formatter that formats Twig templates, locally in your browser",
    minify: false,
    extensions: ["twig"],
  },
  java: {
    id: "java",
    name: "Java",
    title: "Java Formatter and Minifier",
    description: "Java code formatter that formats Java source code, locally in your browser",
    minify: false,
    extensions: ["java"],
  },
  javascript: {
    id: "javascript",
    name: "JavaScript",
    title: "JavaScript Formatter and Minifier",
    description: "JavaScript formatter that formats JavaScript code, locally in your browser",
    minify: true,
    extensions: ["js", "jsx", "mjs"],
  },
  json: {
    id: "json",
    name: "JSON",
    title: "JSON Formatter and Minifier",
    description: "JSON formatter that formats JSON data, locally in your browser",
    minify: true,
    extensions: ["json"],
  },
  jsonc: {
    id: "jsonc",
    name: "JSONC",
    title: "JSONC Formatter",
    description: "JSONC formatter that formats JSON with comments, locally in your browser",
    minify: false,
    extensions: ["jsonc", "code-workspace"],
  },
  json5: {
    id: "json5",
    name: "JSON5",
    title: "JSON5 Formatter",
    description: "JSON5 formatter that formats JSON5 data, locally in your browser",
    minify: false,
    extensions: ["json5"],
  },
  lua: {
    id: "lua",
    name: "Lua",
    title: "Lua Formatter and Minifier",
    description: "Lua code formatter that formats Lua source code, locally in your browser",
    minify: false,
    extensions: ["lua"],
  },
  markdown: {
    id: "markdown",
    name: "Markdown",
    title: "Markdown Formatter and Minifier",
    description: "Markdown formatter that formats Markdown documents, locally in your browser",
    minify: false,
    extensions: ["md", "markdown"],
  },
  mdx: {
    id: "mdx",
    name: "MDX",
    title: "MDX Formatter",
    description: "MDX formatter that formats Markdown with JSX, locally in your browser",
    minify: false,
    extensions: ["mdx"],
  },
  php: {
    id: "php",
    name: "PHP",
    title: "PHP Formatter and Minifier",
    description: "PHP code formatter that formats PHP source code, locally in your browser",
    minify: false,
    extensions: ["php"],
  },
  proto: {
    id: "proto",
    name: "Protocol Buffers",
    title: "Protocol Buffers Formatter and Minifier",
    description: "Protocol Buffers formatter that formats .proto files, locally in your browser",
    minify: false,
    extensions: ["proto"],
  },
  python: {
    id: "python",
    name: "Python",
    title: "Python Formatter and Minifier",
    description: "Python code formatter that formats Python source code, locally in your browser",
    minify: false,
    extensions: ["py", "pyw"],
  },
  rust: {
    id: "rust",
    name: "Rust",
    title: "Rust Formatter and Minifier",
    description: "Rust code formatter that formats Rust source code, locally in your browser",
    minify: false,
    extensions: ["rs"],
  },
  sql: {
    id: "sql",
    name: "SQL",
    title: "SQL Formatter and Minifier",
    description: "SQL formatter that formats SQL queries, locally in your browser",
    minify: false,
    extensions: ["sql"],
  },
  graphql: {
    id: "graphql",
    name: "GraphQL",
    title: "GraphQL Formatter and Minifier",
    description: "GraphQL formatter that formats GraphQL queries and schemas, locally in your browser",
    minify: true,
    extensions: ["graphql", "gql", "graphqls"],
  },
  shell: {
    id: "shell",
    name: "Shell",
    title: "Shell Formatter and Minifier",
    description: "Shell script formatter that formats sh, Bash, Zsh, and Ksh scripts, locally in your browser",
    minify: true,
    extensions: ["sh", "bash", "zsh", "ksh"],
  },
  typescript: {
    id: "typescript",
    name: "TypeScript",
    title: "TypeScript Formatter and Minifier",
    description: "TypeScript formatter that formats TypeScript code, locally in your browser",
    minify: true,
    extensions: ["ts", "tsx"],
  },
  toml: {
    id: "toml",
    name: "TOML",
    title: "TOML Formatter and Minifier",
    description: "TOML formatter that formats TOML configuration files, locally in your browser",
    minify: false,
    extensions: ["toml"],
  },
  xml: {
    id: "xml",
    name: "XML",
    title: "XML Formatter and Minifier",
    description: "XML formatter that formats XML data, locally in your browser",
    minify: true,
    extensions: ["xml"],
  },
  yaml: {
    id: "yaml",
    name: "YAML",
    title: "YAML Formatter and Minifier",
    description: "YAML formatter that formats YAML data, locally in your browser",
    minify: false,
    extensions: ["yaml", "yml"],
  },
  zig: {
    id: "zig",
    name: "Zig",
    title: "Zig Formatter and Minifier",
    description: "Zig code formatter that formats Zig source code, locally in your browser",
    minify: false,
    extensions: ["zig"],
  },
};

// Helper function to get language config by id
export function getLanguageConfig(id: string): LanguageConfig | undefined {
  return LANGUAGES[id];
}

// Helper function to get all languages
export function getAllLanguages(): LanguageConfig[] {
  return Object.values(LANGUAGES);
}

// Helper function to get language by file extension
export function getLanguageByExtension(
  extension: string,
): LanguageConfig | undefined {
  return Object.values(LANGUAGES).find((lang) => lang.extensions.includes(extension.toLowerCase()));
}
