import type { LanguageInfo } from "./types";

export const languageInfoData: LanguageInfo = {
  "json": {
    "title": "JSON Formatter",
    "description":
      "Happy Formatter's JSON Formatter and JSON Validator help to auto format JSON and validate your JSON text. It also provides a tree view that helps to navigate your formatted JSON data.",
    "features": [
      "It helps to validate JSON online with error messages.",
      "It's the only JSON tool that shows the image on hover on Image URL in a tree view.",
      "It's also a JSON Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of JSON data.",
      "JSON File Formatter provides functionality to upload JSON file and download formatted JSON file. This functionality helps to format JSON file.",
      "95% of APIs use JSON to transfer data between client and server. This tool can work as an API formatter.",
      "Supports JSON Graph View of JSON string which works as a JSON debugger or corrector and can format arrays and objects.",
      "Stores data locally for the last JSON formatted in the browser's local storage. This can be used as a Notepad++, Sublime, or VSCode alternative for JSON beautification.",
      "This JSON online formatter can also work as JSON Lint.",
      "Use the auto switch to turn auto-update on or off for beautification.",
      "It uses WebAssembly (WASM) to beautify JSON, making it easy for a human to read and analyze.",
      "Download JSON once it's created or modified, and it can be opened in Notepad++, Sublime, or VSCode alternative.",
      "JSON Format Checker helps to fix the missing quotes; click the setting icon which looks like a screwdriver on the left side of the editor to fix the format.",
    ],
    "additional_info": [
      "How to Create JSON File?",
      "JSON Full Form",
      "What is JSON?",
      "JSON Example with all data types including JSON Array.",
      "Python Pretty Print JSON",
      "Read JSON File Using Python",
      "Validate JSON using PHP",
      "Python Load JSON From File",
    ],
    "tools": [
      "Online JSON Formatter and Online JSON Validator provide JSON converter tools to convert JSON to XML, JSON to CSV, and JSON to YAML. Also includes JSON Editor, JSONLint, JSON Checker, and JSON Cleaner.",
      "Free JSON Formatting Online and JSON Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "JSON Validator",
      "description":
        "JSON Validator Online checks the integrity/syntax of the JSON data based on JavaScript Object Notation (JSON) Data Interchange Format Specifications (RFC).",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a JSON Fixer to repair the error.",
        "To validate JSON you just need internet and no need to install any software.",
        "Your JSON data gets validated in the browser itself.",
      ],
    },
  },
  "javascript": {
    "title": "JavaScript Formatter",
    "description":
      "Happy Formatter's JavaScript Formatter and JavaScript Validator help to auto format JavaScript code and validate your JavaScript text. It also provides a tree view that helps to navigate your formatted JavaScript data.",
    "features": [
      "It helps to validate JavaScript online with error messages.",
      "It's the only JavaScript tool that shows the image on hover on Image URL in a tree view.",
      "It's also a JavaScript Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of JavaScript data.",
      "JavaScript File Formatter provides functionality to upload JavaScript file and download formatted JavaScript file. This functionality helps to format JavaScript file.",
      "95% of APIs use JavaScript to transfer data between client and server. This tool can work as an API formatter.",
      "Supports JavaScript Graph View of JavaScript string which works as a JavaScript debugger or corrector and can format arrays and objects.",
      "Stores data locally for the last JavaScript formatted in the browser's local storage. This can be used as a Notepad++, Sublime, or VSCode alternative for JavaScript beautification.",
      "This JavaScript online formatter can also work as JavaScript Lint.",
      "Use the auto switch to turn auto-update on or off for beautification.",
      "It uses WebAssembly (WASM) to beautify JavaScript, making it easy for a human to read and analyze.",
      "Download JavaScript once it's created or modified, and it can be opened in Notepad++, Sublime, or VSCode alternative.",
      "JavaScript Format Checker helps to fix the missing quotes; click the setting icon which looks like a screwdriver on the left side of the editor to fix the format.",
    ],
    "additional_info": [
      "How to Create JavaScript File?",
      "JavaScript Full Form",
      "What is JavaScript?",
      "JavaScript Example with all data types including JavaScript Array.",
      "Python Pretty Print JavaScript",
      "Read JavaScript File Using Python",
      "Validate JavaScript using PHP",
      "Python Load JavaScript From File",
    ],
    "tools": [
      "Online JavaScript Formatter and Online JavaScript Validator provide JavaScript converter tools to convert JavaScript to XML, JavaScript to CSV, and JavaScript to YAML. Also includes JavaScript Editor, JavaScriptLint, JavaScript Checker, and JavaScript Cleaner.",
      "Free JavaScript Formatting Online and JavaScript Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "JavaScript Validator",
      "description":
        "JavaScript Validator Online checks the integrity/syntax of the JavaScript data based on JavaScript Object Notation (JSON) Data Interchange Format Specifications (RFC).",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a JavaScript Fixer to repair the error.",
        "To validate JavaScript you just need internet and no need to install any software.",
        "Your JavaScript data gets validated in the browser itself.",
      ],
    },
  },
  "typescript": {
    "title": "TypeScript Formatter",
    "description":
      "Happy Formatter's TypeScript Formatter and TypeScript Validator help to auto format TypeScript code and validate your TypeScript text. It also provides a tree view that helps to navigate your formatted TypeScript data.",
    "features": [
      "It helps to validate TypeScript online with error messages.",
      "It's the only TypeScript tool that shows the image on hover on Image URL in a tree view.",
      "It's also a TypeScript Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of TypeScript data.",
      "TypeScript File Formatter provides functionality to upload TypeScript file and download formatted TypeScript file. This functionality helps to format TypeScript file.",
      "95% of APIs use TypeScript to transfer data between client and server. This tool can work as an API formatter.",
      "Supports TypeScript Graph View of TypeScript string which works as a TypeScript debugger or corrector and can format arrays and objects.",
      "Stores data locally for the last TypeScript formatted in the browser's local storage. This can be used as a Notepad++, Sublime, or VSCode alternative for TypeScript beautification.",
      "This TypeScript online formatter can also work as TypeScript Lint.",
      "Use the auto switch to turn auto-update on or off for beautification.",
      "It uses WebAssembly (WASM) to beautify TypeScript, making it easy for a human to read and analyze.",
      "Download TypeScript once it's created or modified, and it can be opened in Notepad++, Sublime, or VSCode alternative.",
      "TypeScript Format Checker helps to fix the missing quotes; click the setting icon which looks like a screwdriver on the left side of the editor to fix the format.",
    ],
    "additional_info": [
      "How to Create TypeScript File?",
      "TypeScript Full Form",
      "What is TypeScript?",
      "TypeScript Example with all data types including TypeScript Array.",
      "Python Pretty Print TypeScript",
      "Read TypeScript File Using Python",
      "Validate TypeScript using PHP",
      "Python Load TypeScript From File",
    ],
    "tools": [
      "Online TypeScript Formatter and Online TypeScript Validator provide TypeScript converter tools to convert TypeScript to XML, TypeScript to CSV, and TypeScript to YAML. Also includes TypeScript Editor, TypeScriptLint, TypeScript Checker, and TypeScript Cleaner.",
      "Free TypeScript Formatting Online and TypeScript Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "TypeScript Validator",
      "description":
        "TypeScript Validator Online checks the integrity/syntax of the TypeScript data based on JavaScript Object Notation (JSON) Data Interchange Format Specifications (RFC).",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a TypeScript Fixer to repair the error.",
        "To validate TypeScript you just need internet and no need to install any software.",
        "Your TypeScript data gets validated in the browser itself.",
      ],
    },
  },
  "css": {
    "title": "CSS Formatter",
    "description":
      "Happy Formatter's CSS Formatter and CSS Validator help to auto format CSS code and validate your CSS text. It also provides a tree view that helps to navigate your formatted CSS data.",
    "features": [
      "It helps to validate CSS online with error messages.",
      "It's the only CSS tool that shows the image on hover on Image URL in a tree view.",
      "It's also a CSS Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of CSS data.",
      "CSS File Formatter provides functionality to upload CSS file and download formatted CSS file. This functionality helps to format CSS file.",
      "95% of APIs use CSS to transfer data between client and server. This tool can work as an API formatter.",
      "Supports CSS Graph View of CSS string which works as a CSS debugger or corrector and can format arrays and objects.",
      "Stores data locally for the last CSS formatted in the browser's local storage. This can be used as a Notepad++, Sublime, or VSCode alternative for CSS beautification.",
      "This CSS online formatter can also work as CSS Lint.",
      "Use the auto switch to turn auto-update on or off for beautification.",
      "It uses WebAssembly (WASM) to beautify CSS, making it easy for a human to read and analyze.",
      "Download CSS once it's created or modified, and it can be opened in Notepad++, Sublime, or VSCode alternative.",
      "CSS Format Checker helps to fix the missing quotes; click the setting icon which looks like a screwdriver on the left side of the editor to fix the format.",
    ],
    "additional_info": [
      "How to Create CSS File?",
      "CSS Full Form",
      "What is CSS?",
      "CSS Example with all data types including CSS Array.",
      "Python Pretty Print CSS",
      "Read CSS File Using Python",
      "Validate CSS using PHP",
      "Python Load CSS From File",
    ],
    "tools": [
      "Online CSS Formatter and Online CSS Validator provide CSS converter tools to convert CSS to XML, CSS to CSV, and CSS to YAML. Also includes CSS Editor, CSSLint, CSS Checker, and CSS Cleaner.",
      "Free CSS Formatting Online and CSS Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "CSS Validator",
      "description": "CSS Validator Online checks the integrity/syntax of the CSS data based on CSS Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a CSS Fixer to repair the error.",
        "To validate CSS you just need internet and no need to install any software.",
        "Your CSS data gets validated in the browser itself.",
      ],
    },
  },
  "html": {
    "title": "HTML Formatter",
    "description":
      "Happy Formatter's HTML Formatter and HTML Validator help to auto format HTML code and validate your HTML text. It also provides a tree view that helps to navigate your formatted HTML data.",
    "features": [
      "It helps to validate HTML online with error messages.",
      "It's the only HTML tool that shows the image on hover on Image URL in a tree view.",
      "It's also a HTML Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of HTML data.",
      "HTML File Formatter provides functionality to upload HTML file and download formatted HTML file. This functionality helps to format HTML file.",
      "95% of APIs use HTML to transfer data between client and server. This tool can work as an API formatter.",
      "Supports HTML Graph View of HTML string which works as a HTML debugger or corrector and can format arrays and objects.",
      "Stores data locally for the last HTML formatted in the browser's local storage. This can be used as a Notepad++, Sublime, or VSCode alternative for HTML beautification.",
      "This HTML online formatter can also work as HTML Lint.",
      "Use the auto switch to turn auto-update on or off for beautification.",
      "It uses WebAssembly (WASM) to beautify HTML, making it easy for a human to read and analyze.",
      "Download HTML once it's created or modified, and it can be opened in Notepad++, Sublime, or VSCode alternative.",
      "HTML Format Checker helps to fix the missing quotes; click the setting icon which looks like a screwdriver on the left side of the editor to fix the format.",
    ],
    "additional_info": [
      "How to Create HTML File?",
      "HTML Full Form",
      "What is HTML?",
      "HTML Example with all data types including HTML Array.",
      "Python Pretty Print HTML",
      "Read HTML File Using Python",
      "Validate HTML using PHP",
      "Python Load HTML From File",
    ],
    "tools": [
      "Online HTML Formatter and Online HTML Validator provide HTML converter tools to convert HTML to XML, HTML to CSV, and HTML to YAML. Also includes HTML Editor, HTMLLint, HTML Checker, and HTML Cleaner.",
      "Free HTML Formatting Online and HTML Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "HTML Validator",
      "description": "HTML Validator Online checks the integrity/syntax of the HTML data based on HTML Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a HTML Fixer to repair the error.",
        "To validate HTML you just need internet and no need to install any software.",
        "Your HTML data gets validated in the browser itself.",
      ],
    },
  },
  "markdown": {
    "title": "Markdown Formatter",
    "description":
      "Happy Formatter's Markdown Formatter and Markdown Validator help to auto format Markdown text and validate your Markdown syntax. It also provides a preview that helps to visualize your formatted Markdown content.",
    "features": [
      "It helps to validate Markdown online with error messages.",
      "It's the only Markdown tool that shows the image on hover on Image URL in a preview.",
      "It's also a Markdown Beautifier that supports various indentation levels.",
      "Supports printing of Markdown data.",
      "Markdown File Formatter provides functionality to upload Markdown file and download formatted Markdown file. This functionality helps to format Markdown file.",
      "Supports Markdown Graph View of Markdown string which works as a Markdown debugger or corrector and can format arrays and objects.",
      "Stores data locally for the last Markdown formatted in the browser's local storage. This can be used as a Notepad++, Sublime, or VSCode alternative for Markdown beautification.",
      "This Markdown online formatter can also work as Markdown Lint.",
      "Use the auto switch to turn auto-update on or off for beautification.",
      "It uses WebAssembly (WASM) to beautify Markdown, making it easy for a human to read and analyze.",
      "Download Markdown once it's created or modified, and it can be opened in Notepad++, Sublime, or VSCode alternative.",
      "Markdown Format Checker helps to fix the missing quotes; click the setting icon which looks like a screwdriver on the left side of the editor to fix the format.",
    ],
    "additional_info": [
      "How to Create Markdown File?",
      "Markdown Full Form",
      "What is Markdown?",
      "Markdown Example with all data types including Markdown Array.",
      "Python Pretty Print Markdown",
      "Read Markdown File Using Python",
      "Validate Markdown using PHP",
      "Python Load Markdown From File",
    ],
    "tools": [
      "Online Markdown Formatter and Online Markdown Validator provide Markdown converter tools to convert Markdown to HTML, Markdown to PDF, and Markdown to DOCX. Also includes Markdown Editor, MarkdownLint, Markdown Checker, and Markdown Cleaner.",
      "Free Markdown Formatting Online and Markdown Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "Markdown Validator",
      "description":
        "Markdown Validator Online checks the integrity/syntax of the Markdown data based on Markdown Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a Markdown Fixer to repair the error.",
        "To validate Markdown you just need internet and no need to install any software.",
        "Your Markdown data gets validated in the browser itself.",
      ],
    },
  },
  "java": {
    "title": "Java Formatter",
    "description":
      "Happy Formatter's Java Formatter and Java Validator help to auto format Java code and validate your Java syntax. It also provides a tree view that helps to navigate your formatted Java code.",
    "features": [
      "It helps to validate Java online with error messages.",
      "It's the only Java tool that shows the image on hover on Image URL in a tree view.",
      "It's also a Java Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of Java data.",
      "Java File Formatter provides functionality to upload Java file and download formatted Java file. This functionality helps to format Java file.",
      "95% of APIs use Java to transfer data between client and server. This tool can work as an API formatter.",
      "Supports Java Graph View of Java string which works as a Java debugger or corrector and can format arrays and objects.",
      "Stores data locally for the last Java formatted in the browser's local storage. This can be used as a Notepad++, Sublime, or VSCode alternative for Java beautification.",
      "This Java online formatter can also work as Java Lint.",
      "Use the auto switch to turn auto-update on or off for beautification.",
      "It uses WebAssembly (WASM) to beautify Java, making it easy for a human to read and analyze.",
      "Download Java once it's created or modified, and it can be opened in Notepad++, Sublime, or VSCode alternative.",
      "Java Format Checker helps to fix the missing quotes; click the setting icon which looks like a screwdriver on the left side of the editor to fix the format.",
    ],
    "additional_info": [
      "How to Create Java File?",
      "Java Full Form",
      "What is Java?",
      "Java Example with all data types including Java Array.",
      "Python Pretty Print Java",
      "Read Java File Using Python",
      "Validate Java using PHP",
      "Python Load Java From File",
    ],
    "tools": [
      "Online Java Formatter and Online Java Validator provide Java converter tools to convert Java to XML, Java to CSV, and Java to YAML. Also includes Java Editor, JavaLint, Java Checker, and Java Cleaner.",
      "Free Java Formatting Online and Java Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "Java Validator",
      "description": "Java Validator Online checks the integrity/syntax of the Java data based on Java Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a Java Fixer to repair the error.",
        "To validate Java you just need internet and no need to install any software.",
        "Your Java data gets validated in the browser itself.",
      ],
    },
  },
  "dart": {
    "title": "Dart Formatter",
    "description": "Dart Formatter that formats Dart data, locally in your browser",
    "features": [
      "It helps to validate Dart online with error messages.",
      "It's the only Dart tool that shows the image on hover on Image URL in a tree view.",
      "It's also a Dart Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of Dart data.",
    ],
    "additional_info": [
      "How to Create Dart File?",
      "Dart Full Form",
      "What is Dart?",
      "Dart Example with all data types including Dart Array.",
      "Python Pretty Print Dart",
      "Read Dart File Using Python",
      "Validate Dart using PHP",
      "Python Load Dart From File",
    ],
    "tools": [
      "Online Dart Formatter and Online Dart Validator provide Dart converter tools to convert Dart to XML, Dart to CSV, and Dart to YAML. Also includes Dart Editor, DartLint, Dart Checker, and Dart Cleaner.",
      "Free Dart Formatting Online and Dart Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "Dart Validator",
      "description": "Dart Validator Online checks the integrity/syntax of the Dart data based on Dart Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a Dart Fixer to repair the error.",
        "To validate Dart you just need internet and no need to install any software.",
        "Your Dart data gets validated in the browser itself.",
      ],
    },
  },
  "go": {
    "title": "Go Formatter",
    "description": "Go Formatter that formats Go data, locally in your browser",
    "features": [
      "It helps to validate Go online with error messages.",
      "It's the only Go tool that shows the image on hover on Image URL in a tree view.",
      "It's also a Go Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of Go data.",
    ],
    "additional_info": [
      "How to Create Go File?",
      "Go Full Form",
      "What is Go?",
      "Go Example with all data types including Go Array.",
      "Python Pretty Print Go",
      "Read Go File Using Python",
      "Validate Go using PHP",
      "Python Load Go From File",
    ],
    "tools": [
      "Online Go Formatter and Online Go Validator provide Go converter tools to convert Go to XML, Go to CSV, and Go to YAML. Also includes Go Editor, GoLint, Go Checker, and Go Cleaner.",
      "Free Go Formatting Online and Go Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "Go Validator",
      "description": "Go Validator Online checks the integrity/syntax of the Go data based on Go Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a Go Fixer to repair the error.",
        "To validate Go you just need internet and no need to install any software.",
        "Your Go data gets validated in the browser itself.",
      ],
    },
  },
  "lua": {
    "title": "Lua Formatter",
    "description": "Lua Formatter that formats Lua data, locally in your browser",
    "features": [
      "It helps to validate Lua online with error messages.",
      "It's the only Lua tool that shows the image on hover on Image URL in a tree view.",
      "It's also a Lua Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of Lua data.",
    ],
    "additional_info": [
      "How to Create Lua File?",
      "Lua Full Form",
      "What is Lua?",
      "Lua Example with all data types including Lua Array.",
      "Python Pretty Print Lua",
      "Read Lua File Using Python",
      "Validate Lua using PHP",
      "Python Load Lua From File",
    ],
    "tools": [
      "Online Lua Formatter and Online Lua Validator provide Lua converter tools to convert Lua to XML, Lua to CSV, and Lua to YAML. Also includes Lua Editor, LuaLint, Lua Checker, and Lua Cleaner.",
      "Free Lua Formatting Online and Lua Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "Lua Validator",
      "description": "Lua Validator Online checks the integrity/syntax of the Lua data based on Lua Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a Lua Fixer to repair the error.",
        "To validate Lua you just need internet and no need to install any software.",
        "Your Lua data gets validated in the browser itself.",
      ],
    },
  },
  "python": {
    "title": "Python Formatter",
    "description": "Python Formatter that formats Python data, locally in your browser",
    "features": [
      "It helps to validate Python online with error messages.",
      "It's the only Python tool that shows the image on hover on Image URL in a tree view.",
      "It's also a Python Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of Python data.",
      "It uses Ruff to format Python code.",
    ],
    "additional_info": [
      "How to Create Python File?",
      "Python Full Form",
      "What is Python?",
      "Python Example with all data types including Python Array.",
      "Python Pretty Print Python",
      "Read Python File Using Python",
      "Validate Python using PHP",
      "Python Load Python From File",
    ],
    "tools": [
      "Online Python Formatter and Online Python Validator provide Python converter tools to convert Python to XML, Python to CSV, and Python to YAML. Also includes Python Editor, PythonLint, Python Checker, and Python Cleaner.",
      "Free Python Formatting Online and Python Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "Python Validator",
      "description":
        "Python Validator Online checks the integrity/syntax of the Python data based on Python Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a Python Fixer to repair the error.",
        "To validate Python you just need internet and no need to install any software.",
        "Your Python data gets validated in the browser itself.",
      ],
    },
  },
  "sql": {
    "title": "SQL Formatter",
    "description": "SQL Formatter that formats SQL data, locally in your browser",
    "features": [
      "It helps to validate SQL online with error messages.",
      "It's the only SQL tool that shows the image on hover on Image URL in a tree view.",
      "It's also a SQL Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of SQL data.",
    ],
    "additional_info": [
      "How to Create SQL File?",
      "SQL Full Form",
      "What is SQL?",
      "SQL Example with all data types including SQL Array.",
      "Python Pretty Print SQL",
      "Read SQL File Using Python",
      "Validate SQL using PHP",
      "Python Load SQL From File",
    ],
    "tools": [
      "Online SQL Formatter and Online SQL Validator provide SQL converter tools to convert SQL to XML, SQL to CSV, and SQL to YAML. Also includes SQL Editor, SQLLint, SQL Checker, and SQL Cleaner.",
      "Free SQL Formatting Online and SQL Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "SQL Validator",
      "description": "SQL Validator Online checks the integrity/syntax of the SQL data based on SQL Specifications.",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a SQL Fixer to repair the error.",
        "To validate SQL you just need internet and no need to install any software.",
        "Your SQL data gets validated in the browser itself.",
      ],
    },
  },
  "default": {
    "title": "Formatter",
    "description": "Formatter that formats data, locally in your browser",
    "features": [
      "It helps to validate data online with error messages.",
      "It's the only data tool that shows the image on hover on Image URL in a tree view.",
      "It's also a data Beautifier that supports indentation levels: 2 spaces, 3 spaces, and 4 spaces.",
      "Supports printing of data.",
    ],
    "additional_info": [
      "How to Create Data File?",
      "Data Full Form",
      "What is Data?",
      "Data Example with all data types including Data Array.",
      "Python Pretty Print Data",
      "Read Data File Using Python",
      "Validate Data using PHP",
      "Python Load Data From File",
    ],
    "tools": [
      "Online Data Formatter and Online Data Validator provide Data converter tools to convert Data to XML, Data to CSV, and Data to YAML. Also includes Data Editor, DataLint, Data Checker, and Data Cleaner.",
      "Free Data Formatting Online and Data Validator work well in Windows, Mac, Linux, Chrome, Firefox, Safari, and Edge.",
    ],
    "validator": {
      "title": "Validator",
      "description": "Validator that validates data, locally in your browser",
      "features": [
        "It's super easy to find the error when line numbers are highlighted with an in-detail error description.",
        "Use the format button as a Data Fixer to repair the error.",
        "To validate Data you just need internet and no need to install any software.",
        "Your Data data gets validated in the browser itself.",
      ],
    },
  },
};
