<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
  version="2.0"
  xmlns:html="http://www.w3.org/1999/xhtml"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
>
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" />
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - HappyFormatter</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
        body {
          font-family:
            -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
            "Helvetica Neue", Arial, sans-serif;
          color: #333;
          max-width: 1200px;
          margin: 0 auto;
          padding: 20px;
          background-color: #f5f5f5;
        }
        h1 {
          color: #2c3e50;
          border-bottom: 3px solid #3498db;
          padding-bottom: 10px;
        }
        .intro {
          background-color: #fff;
          padding: 20px;
          margin: 20px 0;
          border-radius: 8px;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .intro a {
          color: #3498db;
          text-decoration: none;
        }
        .intro a:hover {
          text-decoration: underline;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          background-color: #fff;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
          border-radius: 8px;
          overflow: hidden;
        }
        tr:nth-child(odd) {
          background-color: #f9f9f9;
        }
        th {
          text-align: left;
          padding: 12px;
          background-color: #3498db;
          color: #fff;
          font-weight: 600;
        }
        td {
          padding: 12px;
          border-bottom: 1px solid #eee;
        }
        td a {
          color: #3498db;
          text-decoration: none;
        }
        td a:hover {
          text-decoration: underline;
        }
        .footer {
          margin-top: 30px;
          text-align: center;
          color: #666;
          font-size: 14px;
        }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <div class="intro">
          <p>
            This is an XML Sitemap generated by <a
              href="https://happyformatter.com"
            >HappyFormatter</a>.
            It's used by search engines to discover pages on this website.
          </p>
          <p>
            This sitemap contains <strong><xsl:value-of
                select="count(sitemap:urlset/sitemap:url)"
              /></strong> URL<xsl:if
              test="count(sitemap:urlset/sitemap:url) != 1"
            >s</xsl:if>.
          </p>
        </div>
        <table>
          <tr>
            <th>URL</th>
            <th>Last Modified</th>
            <th>Change Frequency</th>
            <th>Priority</th>
          </tr>
          <xsl:for-each select="sitemap:urlset/sitemap:url">
            <tr>
              <td>
                <xsl:variable name="itemURL">
                  <xsl:value-of select="sitemap:loc" />
                </xsl:variable>
                <a href="{$itemURL}">
                  <xsl:value-of select="sitemap:loc" />
                </a>
              </td>
              <td>
                <xsl:value-of
                  select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"
                />
              </td>
              <td>
                <xsl:value-of select="sitemap:changefreq" />
              </td>
              <td>
                <xsl:value-of select="sitemap:priority" />
              </td>
            </tr>
          </xsl:for-each>
        </table>
        <div class="footer">
          <p>
            Generated by <a href="https://happyformatter.com">HappyFormatter</a>
            |
            <a href="https://www.sitemaps.org/">Sitemaps.org</a>
          </p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
